name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile score_converter_fixed.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: score_converter_win
        path: dist/score_converter_fixed.exe
